name: Hello-world 

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test_django_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run hello world
        run: |
          echo "hello world"
          echo "${{ secrets.DJANGO_SECRET_KEY }}"
      - name: setup python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install requirements
        run: |
          python -m pip install pip --upgrade 
          python -m pip install -r requirements.txt
      - name: run tests
        run: |
          python manage.py test
