name: Hello-world 

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test_django_project:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: "thi-is-it"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run hello world
        run: |
          echo "hello world"
          echo "${{ env.DJANGO_SECRET_KEY }}"
      - name: setup python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install requirements
        run: |
          pip3 install -r requirements.txt
      - name: run tests
        run: |
          python3.10 manage.py test
