name: Hello-world 

on:
  workflow_dispatch:

jobs:
  test_django_project:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: "thi-is-it"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run hello world
        uses: |
          echo "hello world"
          echo "${{ env.DJANGO_SECRET_KEY }}"