name: 1 - Django Tests MySQL

# Controls when the workflow will run
on:
  # Allows you to call this workflow within another workflow
  workflow_call:
    secrets:
        DJANGO_SECRET_KEY:
          required: true
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggered based on the git event type
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  django_mysql:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Add in environment variables for the entire "build" job
    env:
      MYSQL_DATABASE: cfeblog_db
      MYSQL_USER: cfe_blog_user # do *not* use root; cannot re-create the root user
      MYSQL_ROOT_PASSWORD: 2mLTcmdPzU2LOa0TpAlLPoNf1XtIKsKvNn5WBiszczs
      MYSQL_TCP_PORT: 3306
      MYSQL_HOST: 127.0.0.1
      GITHUB_ACTIONS: true
      DJANGO_SECRET_KEY: "${{ secrets.DJANGO_SECRET_KEY }}"
      DATABASE_BACKEND: mysql
    services:
      mysql:
        image: mysql:8.0.28
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_HOST: ${{ env.MYSQL_HOST }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s 
    # If you want to test multiple python version(s)
    # strategy:
    #   matrix:
    #     python-version: ["3.8", "3.9", "3.10"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          python3.10 -m pip install pip --upgrade
          python3.10 -m pip install -r requirements.txt
      - name: Run Tests
        # Step specific environment variables
        env:
          DEBUG: "0"
          MYSQL_USER: "root" # must use the root user on MySQL to run tests
          DATABASE_BACKEND: ${{ env.DATABASE_BACKEND }}
          DJANGO_SECRET_KEY: ${{ env.DJANGO_SECRET_KEY }}
        run: |
          python manage.py test